# Generated by Django 5.1.2 on 2024-10-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accounts_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
